### ISSUE TITLE
Deal with leading - `#` comments and headers

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#1]
Would be good to have this - for astropy tables, it makes the column assignment much neater if we can have a one-line header!

**Comment by SzymonPrajs** [comment]
@RobFirth Empty lines and those starting with `#`  should now be ignored. Can you test this by pulling the latest `develop` branch before I push this to `master`?

**Comment by RobFirth** [comment]
Great - Thanks. I will do it ASAP.

**Comment by RobFirth** [comment]
Tested with `SN2009jf.dat` which has the following header: `# MJD flux flux_err filter`. Previously if run with a commented file, the code would hang when creating the `recon` file. This behaviour is not seen. Looks good:


![image](https://cloud.githubusercontent.com/assets/10420166/22649053/45539d24-ec71-11e6-95f3-3cb9c50e7cbe.png)

Also tested `SN2005hg` with the same header, and some blank lines. Ran fine, good result

![image](https://cloud.githubusercontent.com/assets/10420166/22649178/c276d0c8-ec71-11e6-8d6d-338cb57f7b49.png)
