### ISSUE TITLE
Add a Python wrapper for LCSim

### ISSUE THREAD

**Issue by SzymonPrajs** [UoS-SNe/CoCo#19]
In the current set up LCSim is very IO intensive making it the biggest bottle neck in the code. Implementing a Python wrapper written in Cython should reduce the overall amount of IO when run directly as part of large LSST simulations.

**Comment by RobFirth** [comment]
Think this one can be closed @SzymonPrajs? Now we have `pyCoCo.CoCo.simulate`

**Comment by SzymonPrajs** [comment]
We definitely need to add some documentation for the wrapper but that's a separate issue so I'm happy to close it. I should also bump the code version to v0.7.0
