### ISSUE TITLE
Passing 0 to python sims class "PyCoCo" for no extinction returns 0 flux 

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#29]
Higher the extinction, the higher the flux - eh?

**Comment by RobFirth** [comment]
Somewhat related issue - small values of extinction blow up the returned flux, **_monochromatically_**.

For example:

```
flux, flux_err = coco.simulate(b"SN2009jf", 
                    0.008, 0.0, 0.1, 0.1, 3.1, 
                    mjdmax, mjd_to_sim, 
                    filters_to_sim)
```

returns:
![sn2009jf_02-05-17_download](https://cloud.githubusercontent.com/assets/10420166/25616049/7ac666f4-2f32-11e7-9c47-69ac7d6de626.png)

but when the extinction is reduced by a factor of 10 to 0.01

```
flux, flux_err = coco.simulate(b"SN2009jf", 
                    0.008, 0.0, 0.01, 0.01, 3.1, 
                    mjdmax, mjd_to_sim, 
                    filters_to_sim)
```

the peak flux changes by ~ 2 orders of magnitude

![sn2009jf_02-05-17_1_download](https://cloud.githubusercontent.com/assets/10420166/25616109/c1a3e01a-2f32-11e7-98dc-5867a3a01f24.png)

and further

```
flux, flux_err = coco.simulate(b"SN2009jf", 
                    0.008, 0.0, 0.00001, 0.00001, 3.1, 
                    mjdmax, mjd_to_sim, 
                    filters_to_sim)
```
![sn2009jf_02-05-17_2_download](https://cloud.githubusercontent.com/assets/10420166/25616130/e20200f8-2f32-11e7-88e1-b32922563000.png)

**Comment by RobFirth** [comment]
Also, the colours are way off compared with the source, SN2009jf, with the shape completely different
![sn2009jf_02-05-17_observed_download](https://cloud.githubusercontent.com/assets/10420166/25616251/803c22d0-2f33-11e7-939a-17515c21ca31.png)
 
for example, BessellB
# Observed
![sn2009jf_02-05-17_observed_bessellb_download](https://cloud.githubusercontent.com/assets/10420166/25616316/d07406f0-2f33-11e7-868e-0dbd29bcd7cc.png)

# Simulated
![sn2009jf_02-05-17_2_bessellb_download](https://cloud.githubusercontent.com/assets/10420166/25616329/de1db5ee-2f33-11e7-9539-e3cbc2dfccd2.png)

**Comment by RobFirth** [comment]
mangled spectra look ok

![sn2009jf_02-05-17_mangledspec_-download](https://cloud.githubusercontent.com/assets/10420166/25616518/2d9691bc-2f35-11e7-9be2-e279bb4d28a3.png)

compared to specseries

![sn2009jf_02-05-17_spec_download](https://cloud.githubusercontent.com/assets/10420166/25616548/5b652a72-2f35-11e7-99ea-e08d40fbc782.png)

**Comment by RobFirth** [comment]
Issue seems to persist when extinction steps are commented out in `LCSim.cpp` and code recompiled. Would be good to reproduce issue on someone else's machine. e.g.  @SzymonPrajs 

edit - think something is wrong with the steps I'm taking to compile - no changes (at all) seen since commenting. Will check.

edit2 - was commenting the wrong part of the code. Changes now seen

**Comment by SzymonPrajs** [comment]
I finally found the source of the problem: Filters.CCM89() was calculating the extinction values in magnitudes while the the rest of the code works in fluxes.
