### ISSUE TITLE
Case Insensitivity in Filter Names

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#3]
This would be super helpful - UBVRI and ugriz systems overlap meaning code cannot distiguish between U and u, R and r or I and i.

**Comment by RobFirth** [comment]
This is essentially a MacOS problem. Need to work out data-side approach to deal with it - i.e. clearly defined filter naming convention.

**Comment by SzymonPrajs** [comment]
This is an OS issue which would be quite difficult to deal with from the code side. Our, and satisfactory, solution is to make all filter names unambiguous by expanding their name with the filter system e.g. `SDSS_g`.
