### ISSUE TITLE
Double Peaked Simulated LCs 

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#34]
Weird one I can't work out. 
Get the following results from the following calls:

## SN2007uy @ z = 0.1

```
snname = b"SN2007uy"
mjdmax = 60054.5
z_obs = 0.1
mjd_to_sim = [ 59580.033829  59580.034275  59580.034722 ...,  63229.361186  63229.361633
  63229.362084]
filters_to_sim = [b'LSST_y' b'LSST_y' b'LSST_y' ..., b'LSST_y' b'LSST_y' b'LSST_y']

flux, flux_err = coco.simulate(snname, 
                    z_obs, 0.0, MW_EBV, host_EBV, 3.1, 
                    mjdmax, mjd_to_sim, 
                    filters_to_sim)
```

![sn2007uy_double_peak](https://cloud.githubusercontent.com/assets/10420166/25859885/c19f8286-34d7-11e7-92d3-a4280c3916dd.png)

## SN2009jf @ z = 0.1
and `snname = b"SN2009jf"`

![sn2009jf_double_peak](https://cloud.githubusercontent.com/assets/10420166/25859901/cfa0153a-34d7-11e7-9ddb-5e7f7bc2a4ab.png)

# Fits

However the LCfits look OK:

## SN2007uy

![sn2007uy_lcfit](https://cloud.githubusercontent.com/assets/10420166/25860029/2da90092-34d8-11e7-8c9d-5a3e866d3e97.png)

## SN2009jf

![sn2009jf_lcfit](https://cloud.githubusercontent.com/assets/10420166/25859988/12400b52-34d8-11e7-8676-2c4b3a0d552e.png)

**Comment by RobFirth** [comment]
So it looks like this is an issue with unconstrained fits at early times. It might actually be unhelpful to have the LC fits above, as the fit that is important for the simulation is that which is made to the spectrophotometry. It might be helpful to have this as an output at some point @SzymonPrajs

**Comment by SzymonPrajs** [comment]
Problem here was the same as in issue #35 hence it is now closed. There are still some issues with the light curves being purely constrained if there are not sufficiently many points either prior or after the maximum light. This should be discussed in a separate issue.
