### ISSUE TITLE
Light Curve Shape Differences Real vs Sim

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#36]
Marked difference between the real and simulated lightcurve shapes. Not sure whether it is linked to the flux offset in https://github.com/UoS-SNe/CoCo/issues/35 . 
![sn2009jf_bessellv_real_vs_sim_2point9mag_offset](https://cloud.githubusercontent.com/assets/10420166/26200578/aa1d9d3c-3bc6-11e7-9ddc-5f895df2ec41.png)

One thing it could be is that the fit to the spectrophotometry is poor (although I don't think that is all of it), it would be good to have a way of outputting the specphot used by `pyCoCo.simulate`

**Comment by SzymonPrajs** [comment]
There is now a `spec_photometry()` function in the pyCoCo wrapper, however, it still need a some work. In it's current state it can only print the spectra photometry into the console but does not return any values. This will be fixes soon.

**Comment by SzymonPrajs** [comment]
After fixing issues #35 and #5 light curve shapes are now exactly as you would expect them to be.
![mangling](https://cloud.githubusercontent.com/assets/5939928/26461199/3b1d7e30-4174-11e7-9bfa-d5f5aca63ac9.png)
