### ISSUE TITLE
Problems building with GridPP version of Minuit2

### ISSUE THREAD

**Issue by djwhiteastro** [UoS-SNe/CoCo#39]
I added paths to EUPS-enabled minuit2 package, and changed flags to account for capital 'M' naming convention as below: 
CXXFLAGS = -c -O3 -fPIC -std=c++0x -I $(GSL_DIR)/include -I $(MINUIT2_DIR)/include
LDFLAGS = -L $(GSL_DIR)/lib -lgsl -lgslcblas -L $(MINUIT2_DIR)/lib -lMinuit2

but I'm getting the following error:
g++ src/core/utils.o src/core/Filters.o src/core/Cosmology.o src/core/SN.o src/core/Solver.o src/solvers/priors.o src/solvers/MNest.o src/solvers/Minuit.o src/core/Model.o src/models/Karpenka12.o src/models/Bazin09.o src/models/Kessler10.o src/models/Firth17Complex.o src/models/SpecMangle.o src/models/LinearMangle.o python/CoCo.o src/LCSim.o -L /cvmfs/lsst.opensciencegrid.org/fnal/products/Linux64/external/gsl/1.15+1/lib -lgsl -lgslcblas -L /cvmfs/lsst.opensciencegrid.org/fnal/products/Linux64/external/minuit2/5.22.00+1/lib -lMinuit2 -o lcsim
src/solvers/MNest.o: In function `MNest::fit()':
MNest.cpp:(.text+0x4d8): undefined reference to `__nested_MOD_nestrun'
collect2: error: ld returned 1 exit status
make: *** [lcsim] Error 1

**Comment by SzymonPrajs** [comment]
I think this was just a left over reference to `MultiNest` which isn't used in the gridPP version of the code. It should be working now.
