### ISSUE TITLE
More than one missing filter causes interpolation error

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#4]
When a filter is not found, mean wavelength is replaced with 0. More than one 0 means that the values passed to the spline are not increasing, causing the following error:

`gsl: interp.c:83: ERROR: x values must be strictly increasing`

**Comment by SzymonPrajs** [comment]
This is a particularly annoying bug. The code doesn't know anything about the filters at the point where it would be the easiest to fix it and by the time it becomes a problem we would have to scan though all data looking for missing filters which would add a lot of unnecessary overheads to most good light curves. I think this would, yet again, be much easier to deal at the level of the Python interface. If you agree with this @RobFirth then I will let you close this issue.
