### ISSUE TITLE
Recon Spectra Naming Convention

### ISSUE THREAD

**Issue by RobFirth** [UoS-SNe/CoCo#6]
Just wanted to clarify the naming convention - the result of a `specfit` run is a `$SNNAME$SPEC_OBS_MJD.spec` and  `$SNNAME$SPEC_OBS_MJD.stat` file.
Is there any way we can consistently keep track of the original spectrum?
My instinct would be to have a commented header with the source file, the run datetime and version, rather than changing the name, which seems to be a reasonable way of doing it?

**Comment by SzymonPrajs** [comment]
That's a good idea. The naming convention is needed to simplify the input for `specphase` and `lcsim`. I will implement this once we add support for ignoring `#` comments in `vmath::loadtxt`.

**Comment by RobFirth** [comment]
I had a feeling you had done it for a IO reason since it isn't the most readable. Sounds like it should be a reasonable compromise to have a header once that is viable. Job for next week!
